services:
  app:
    image: node:20-alpine
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5001:5001'
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/task-manage
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=JWT_SECRET
      - JWT_EXPIRE=1h
      - JWT_REFRESH_SECRET=JWT_REFRESH_SECRET
      - JWT_REFRESH_EXPIRE=7d
    command: sh -c "npm install && npm start"

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - '6378:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
