services:
  app:
    image: node:20-alpine
    restart: always
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - logs:/app/logs
    ports:
      - '5001:5001'
    depends_on:
      - mongo
      - redis
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRE=${JWT_REFRESH_EXPIRE}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - EMAIL_SENDER_ID=${EMAIL_SENDER_ID}
    command: sh -c "npm install && npm start"

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    container_name: redis_server
    ports:
      - '6378:6379'
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
  logs:
